development:
  cloud_name: "dzirffrnn"
  api_key: "522865645676167"
  api_secret: "Z--KpFrKCyzgGGLga_kHwbD3yiw"
  secure: true


production:
  cloud_name: "dzirffrnn"
  api_key: "522865645676167"
  api_secret: "Z--KpFrKCyzgGGLga_kHwbD3yiw"
  secure: true
